CRUD
backmeupplz/backend-starter pull request #29
Opened 2021-03-20 12:08 UTC by mormo669

Created message.ts and schema.ts

2021-03-20 13:07 UTC, backmeupplz requested changes

2021-03-20 13:07 UTC, backmeupplz commented on src/models/schema.ts
> +import { prop, getModelForClass, DocumentType } from '@typegoose/typegoose'
Этот файл должен называться `message.ts`, если это файл со схемой сообщения.

2021-03-20 13:07 UTC, backmeupplz commented on src/controllers/message.ts
> +import { getOrCreateMessage, MessageModel } from '../models/schema'
У нас тут используются умные импорты, привыкай к ним. Вместо бесконечных `../../..` мы пишем вот так: `import { runMongo } from '@/models/index'`

2021-03-20 13:07 UTC, backmeupplz commented on src/controllers/message.ts
> +
Либо делай linebreaks между рутами, либо не делай. В стиле кода важна постоянность.

2021-03-20 13:07 UTC, backmeupplz commented on src/models/schema.ts
> +export class Message {
У сообщения должен быть автор типа User.

2021-03-20 13:07 UTC, backmeupplz commented on src/models/schema.ts
> +export async function getOrCreateMessage(msg: Message) {
Ты тут не ищешь сообщения, поэтому можно просто назвать эту функцию `createMessage`. Называй функции и переменные понятно.

2021-03-20 13:07 UTC, backmeupplz commented on src/models/schema.ts
> +  let message: DocumentType<Message> | undefined
Весь этот танец с переменными не нужен. Просто сделай `return new MessageModel(msg).save()`

2021-03-20 13:07 UTC, backmeupplz commented on yarn.lock
>    resolved "https://registry.yarnpkg.com/diff-sequences/-/diff-sequences-26.6.2.tgz#48ba99157de1923412eed41db6b6d4aa9ca7c0b1"
В локфайле не должно быть изменений.

2021-03-20 13:07 UTC, backmeupplz commented on src/controllers/message.ts
> +  async updateMessage(@Ctx() ctx: Context) {
Нужна middleware, которая проверит, что это сообщение принадлежит этому автору — иначе все могут удалять сообщения всех, это плохо. Эту миддлварю нужно использовать во всех рутах, где нужно проверять принадлежность сообщения юзеру.

2021-03-20 13:07 UTC, backmeupplz commented on src/controllers/message.ts
> +  async addMessage(@Ctx() ctx: Context) {
Создай middleware, которая будет аутентифицировать человека и используй ее везде, где надо.

Вот пример:

```typescript
export async function authenticate(ctx: Context, next: Function) {
  try {
    const token = ctx.headers.token
    if (!token) {
      return ctx.throw(403, errors.noTokenProvided)
    }
    const user = await getUserFromToken(token)
    if (!user) {
      return ctx.throw(403, errors.noUser)
    }
    ctx.state.user = user
  } catch (err) {
    await report(err)
    return ctx.throw(403, errors.authentication)
  }
  await next()
}
```

2021-03-20 13:07 UTC, backmeupplz commented on src/controllers/message.ts
> +    let msg = await MessageModel.findById(
Мы должны получать не все сообщения, а только для определенного пользователя.

2021-04-06 14:05 UTC, backmeupplz requested changes

2021-04-06 14:05 UTC, backmeupplz commented on src/controllers/message.ts
> +async function authMiddleware(ctx: Context, next) {
Вынеси миддлварю в отдельный файл в папке `/src/middlewares`, например

2021-04-06 14:05 UTC, backmeupplz commented on src/controllers/message.ts
> +    await next()
Лучше сделать `return next()`

2021-04-06 14:05 UTC, backmeupplz commented on src/controllers/message.ts
> +  @Post('/save')
Можешь сделать просто `@Post('/')` тут

2021-04-06 14:05 UTC, backmeupplz commented on src/controllers/message.ts
> +      console.log(message.user)
`console.log` разные лучше не кидать в пуллреквестах, убери их

2021-04-06 14:05 UTC, backmeupplz commented on src/controllers/message.ts
> +  @Get('/read')
Можно сделать просто `@Get('/')`

2021-04-06 14:05 UTC, backmeupplz commented on src/controllers/message.ts
> +  @Delete('/del/:id')
Можешь сделать просто `@Delete('/:id')`

2021-04-06 14:05 UTC, backmeupplz commented on src/controllers/message.ts
> +  @Put('/upd/:id')
Можешь сделать просто `@Put('/:id')`

2021-04-06 14:05 UTC, backmeupplz commented on src/controllers/message.ts
> +      return ctx.throw(400, 'Failed to delete message')
Почитай про HTTP статусы. 4xx — это ошибка запроса, у тебя же тут должен быть 5xx

2021-04-06 14:05 UTC, backmeupplz commented on src/controllers/message.ts
> +      return ctx.throw(400, 'Failed to delete message')
В других местах тоже проверь

2021-04-06 14:05 UTC, backmeupplz commented on yarn.lock
> +  integrity sha512-faQrqNMzcPCHGVC2aaOINk13K+aaBDUPjGWl0teOXywElLjyVAB6Oe2jj62jHYtwsU49jXhScYbvPENK+6zAvQ==
В этом файле не должно быть изменений

2021-04-06 14:05 UTC, backmeupplz commented on src/models/index.ts
> +    useFindAndModify: false,
Зачем это изменение?

2021-04-06 14:19 UTC, mormo669 commented on src/models/index.ts
> +    useFindAndModify: false,
Не сохранялось без него, а как поправил все сохранилось

2021-05-01 01:26 UTC, closed without merging